import { ensureEnv } from '@take-out/helpers'

if (typeof window !== 'undefined') {
  throw new Error(`This is a server-only file`)
}

// 🔒 start - this is generated by "bun env:update"
export const AWS_ACCESS_KEY_ID = ensureEnv('AWS_ACCESS_KEY_ID', "")
export const AWS_SECRET_ACCESS_KEY = ensureEnv('AWS_SECRET_ACCESS_KEY', "")
export const APNS_ENDPOINT = ensureEnv('APNS_ENDPOINT', "https://api.sandbox.push.apple.com")
export const APNS_TEAM_ID = ensureEnv('APNS_TEAM_ID', "")
export const APNS_KEY_ID = ensureEnv('APNS_KEY_ID', "")
export const APNS_KEY = ensureEnv('APNS_KEY', "")
export const BETTER_AUTH_SECRET = ensureEnv('BETTER_AUTH_SECRET')
export const BETTER_AUTH_URL = ensureEnv('BETTER_AUTH_URL')
export const CLOUDFLARE_R2_ACCESS_KEY = ensureEnv('CLOUDFLARE_R2_ACCESS_KEY')
export const CLOUDFLARE_R2_ENDPOINT = ensureEnv('CLOUDFLARE_R2_ENDPOINT')
export const CLOUDFLARE_R2_PUBLIC_URL = ensureEnv('CLOUDFLARE_R2_PUBLIC_URL')
export const CLOUDFLARE_R2_SECRET_KEY = ensureEnv('CLOUDFLARE_R2_SECRET_KEY')
export const DEPLOYMENT_PLATFORM = ensureEnv('DEPLOYMENT_PLATFORM', "uncloud")
export const DEPLOYMENT_ARCH = ensureEnv('DEPLOYMENT_ARCH', "linux/amd64")
export const DEPLOY_HOST = ensureEnv('DEPLOY_HOST', "")
export const DEPLOY_USER = ensureEnv('DEPLOY_USER', "root")
export const DEPLOY_SSH_KEY = ensureEnv('DEPLOY_SSH_KEY', "")
export const DEPLOY_DB = ensureEnv('DEPLOY_DB', "")
export const ONE_SERVER_URL = ensureEnv('ONE_SERVER_URL')
export const POSTMARK_SERVER_TOKEN = ensureEnv('POSTMARK_SERVER_TOKEN')
export const VITE_DEMO_MODE = ensureEnv('VITE_DEMO_MODE', "")
export const VITE_POSTHOG_API_KEY = ensureEnv('VITE_POSTHOG_API_KEY', "")
export const VITE_POSTHOG_HOST = ensureEnv('VITE_POSTHOG_HOST', "")
export const VITE_ZERO_HOST = ensureEnv('VITE_ZERO_HOST', "")
export const VITE_WEB_HOST = ensureEnv('VITE_WEB_HOST', "")
export const ZERO_NUM_SYNC_WORKERS = ensureEnv('ZERO_NUM_SYNC_WORKERS', "2")
export const ZERO_CVR_MAX_CONNS = ensureEnv('ZERO_CVR_MAX_CONNS', "4")
export const ZERO_UPSTREAM_MAX_CONNS = ensureEnv('ZERO_UPSTREAM_MAX_CONNS', "8")
export const ZERO_PER_USER_MUTATION_LIMIT_MAX = ensureEnv('ZERO_PER_USER_MUTATION_LIMIT_MAX', "30")
export const ZERO_PER_USER_MUTATION_LIMIT_WINDOW_MS = ensureEnv('ZERO_PER_USER_MUTATION_LIMIT_WINDOW_MS', "60000")
export const ZERO_MUTATE_FORWARD_COOKIES = ensureEnv('ZERO_MUTATE_FORWARD_COOKIES', "true")
export const ZERO_QUERY_FORWARD_COOKIES = ensureEnv('ZERO_QUERY_FORWARD_COOKIES', "true")
export const ZERO_APP_PUBLICATIONS = ensureEnv('ZERO_APP_PUBLICATIONS', "zero_takeout")
export const ZERO_VERSION = ensureEnv('ZERO_VERSION')
// 🔒 end - this is generated by "bun env:update"

// database urls set by sst or uncloud conditionally based on deployment
// use bracket notation to prevent build-time inlining
export const ZERO_UPSTREAM_DB = process.env['ZERO_UPSTREAM_DB'] || ''
export const ZERO_CVR_DB = process.env['ZERO_CVR_DB'] || ''
export const ZERO_CHANGE_DB = process.env['ZERO_CHANGE_DB'] || ''
