/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Postgres2": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "PostgresMigrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "VPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "WebApp": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "Zero4": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "ZeroReplication4": {
      "service": string
      "type": "sst.aws.Service"
    }
    "ZeroReplicationBucket4": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}