#!/usr/bin/env bun

import fs from 'node:fs'

import { cmd } from './cmd'
import { resolveDepVersion } from './helpers/resolve-dep-version'

await cmd`sync environment variables from package.json to CI and server configs`.run(
  async () => {
    const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf-8'))
    const envVars = packageJson.env as Record<string, boolean | string>

    if (!envVars || Array.isArray(envVars) || typeof envVars !== 'object') {
      console.error('No environment variables found in package.json')
      process.exit(1)
    }

    const markerStart = '🔒 start - this is generated by "bun env:update"'
    const markerEnd = '🔒 end - this is generated by "bun env:update"'

    const yamlStartMarker = `# ${markerStart}`
    const yamlEndMarker = `# ${markerEnd}`

    const jsStartMarker = `// ${markerStart}`
    const jsEndMarker = `// ${markerEnd}`

    function replaceYamlSection(
      content: string,
      lines: string,
      options: { indent: string }
    ): string {
      return content.replace(
        new RegExp(`${yamlStartMarker}(.|\n)*?${yamlEndMarker}`, 'gm'),
        `${yamlStartMarker}\n${lines}\n${options.indent}${yamlEndMarker}`
      )
    }

    function updateDeployYml() {
      const deployYmlPath = '.github/workflows/ci.yml'
      let deployYml = fs.readFileSync(deployYmlPath, 'utf-8')

      if (!deployYml.includes(yamlStartMarker) || !deployYml.includes(yamlEndMarker)) {
        throw new Error(`Markers not found in ${deployYmlPath}`)
      }

      const indent = `          `
      const envSection = Object.entries(envVars)
        .map(([key, value]) => {
          const resolved = resolveDepVersion(value, packageJson.dependencies)
          if (resolved) {
            return `${indent}${key}: \${{ secrets.${key} || '${resolved}' }}`
          }
          return `${indent}${key}: \${{ secrets.${key} }}`
        })
        .join('\n')

      const newDeployYml = replaceYamlSection(deployYml, envSection, { indent })

      fs.writeFileSync(deployYmlPath, newDeployYml, 'utf-8')
      console.info('✅ Updated Github workflow')
    }

    function updateEnvServerTs() {
      const candidates = ['src/constants/env-server.ts', 'src/server/env-server.ts']
      let envServerPath = ''
      let envServer = ''

      for (const p of candidates) {
        try {
          envServer = fs.readFileSync(p, 'utf-8')
          envServerPath = p
          break
        } catch {}
      }

      if (!envServerPath) {
        throw new Error(`env-server.ts not found at ${candidates.join(' or ')}`)
      }

      if (!envServer.includes(jsStartMarker) || !envServer.includes(jsEndMarker)) {
        throw new Error(`Markers not found in ${envServerPath}`)
      }

      const envExports = Object.entries(envVars)
        .map(([key, value]) => {
          // $dep: values have no compile-time default — resolved into .env at runtime
          if (typeof value === 'string' && value.startsWith('$dep:')) {
            return `export const ${key} = ensureEnv('${key}')`
          }
          return `export const ${key} = ensureEnv('${key}'${typeof value === 'string' ? `, ${JSON.stringify(value)}` : ''})`
        })
        .join('\n')

      const newEnvServer = envServer.replace(
        new RegExp(`${jsStartMarker}(.|\n)*?${jsEndMarker}`, 'm'),
        `${jsStartMarker}\n${envExports}\n${jsEndMarker}`
      )

      fs.writeFileSync(envServerPath, newEnvServer, 'utf-8')
      console.info('✅ Updated server env')
    }

    function updateDockerCompose() {
      const dockerComposePath = 'src/uncloud/docker-compose.yml'

      let dockerCompose = ''
      try {
        dockerCompose = fs.readFileSync(dockerComposePath, 'utf-8')
      } catch (_error) {
        // file doesn't exist, skip
        return
      }

      if (
        !dockerCompose.includes(yamlStartMarker) ||
        !dockerCompose.includes(yamlEndMarker)
      ) {
        // no markers, skip
        return
      }

      // detect indent from the marker line
      const markerMatch = dockerCompose.match(
        new RegExp(`^(\\s*)${yamlStartMarker}`, 'm')
      )
      const indent = markerMatch?.[1] || '      '

      // detect format: if markers are under an x- anchor block, use map syntax (KEY: val)
      // otherwise use list syntax (- KEY=val)
      const beforeMarker = dockerCompose.slice(0, dockerCompose.indexOf(yamlStartMarker))
      const isMap = /x-[\w-]+:.*&[\w-]+/s.test(beforeMarker)

      const envLines = Object.entries(envVars)
        .map(([key, value]) => {
          const resolved = resolveDepVersion(value, packageJson.dependencies)
          const defaultVal = resolved || (typeof value === 'string' ? value : '')
          return isMap
            ? `${indent}${key}: \${${key}:-${defaultVal}}`
            : `${indent}- ${key}=\${${key}:-${defaultVal}}`
        })
        .join('\n')

      const newDockerCompose = replaceYamlSection(dockerCompose, envLines, { indent })

      fs.writeFileSync(dockerComposePath, newDockerCompose, 'utf-8')
      console.info('✅ Updated docker-compose.yml')
    }

    try {
      updateDeployYml()
      updateEnvServerTs()
      updateDockerCompose()
      console.info('✅ All files updated successfully')
    } catch (error: any) {
      console.error('❌ Update failed:', error.message)
      process.exit(1)
    }
  }
)
